

package Entidades;

/**
 *
 * @author Julian Rios
 */
public enum Especialidad {
    SELECCIONAR_ESPECIALIDAD,INCENDIO_EN_VIVIENDA,INCENDIO_EN_INDUSTRIA, SOCORRO_EN_DERRUMBE, SOCORRO_AMBITO_DE_MONTAÑA, SOCORRO_ACCIDENTE_DE_TRANSITO, SOCORRO_INUNDACIONES, SOCORRO_EN_ALTURA, PREVENCION;

}
